### ISSUE TITLE
Using Homebrew in OS X

### ISSUE THREAD

**Issue by wonook** [snu-sf/pl2015#1]
I think that using Homebrew for installing coq is a convenient way of downloading and installing coq on mac OS X. I've just tried it for myself, and it seems to be working fine with the right versions (8.4pl5). Maybe this can be instructed in the course instruction manuals.
With Homebrew installed, all you have to do is

```
$ brew install coq
```

and if you want to install opam, it can be done by

```
$ brew install opam
```

It seems like the steps like `./configure ..` and `make world` are all included in `$ brew install coq` as well. No extra bash settings to do.
It's just a small suggestion that seems like a fine solution that does all the work for you.

**Comment by jeehoonkang** [comment]
That's a great comment, and I will update the README soon.

Thanks,

**Comment by wonook** [comment]
for more information about Homebrew: http://brew.sh/

**Comment by wonook** [comment]
Thanks for taking it into consideration!

**Comment by wonook** [comment]
~~**+** Just for sharing!~~
~~I'm personally a vim user, so for those like me, [coq.vim](https://github.com/jvoorhis/coq.vim) seems like a decent vim pathogen plugin for syntax highlighting + indentation.~~
CoqIDE looks better for this class

**Comment by wonook** [comment]
To install coqide it's easy if you use [Brew Cask](http://caskroom.io/)
1. `$ brew install caskroom/cask/brew-cask`
2. `$ brew cask install coqide`
3. Done

After then, you'll be able to spot your coqtop file with

```
$ which coqtop
```

if needed.
