### ISSUE TITLE
Wildcard for destruct as?

### ISSUE THREAD

**Issue by jaewooklee93** [snu-sf/pl2015#102]
In homework, I tried to write

``` Coq
destruct a1 as [n1|x1|a1_1 a1_2|a1_1 a1_2|a1_1 a1_2]; try destruct n1;
```

However, I only need `n1` and the remaining names are not necessary.
Can I just leave them blank? like `[n1||||]`, or is it impossible?

**Comment by jeehoonkang** [comment]
- Blank is good.
- If you want to place something, put `?`.
- Try putting `_` and see if what happens :-)

**Comment by jaewooklee93** [comment]
I already tried several ways which seem reasonable, but

`destruct a1 as [n1||||]; try destruct n1;`
gave
`Syntax error: "|" or "]" expected (in [disjunctive_intropattern])`.
and
 `destruct a1 as [n1|_|_|_|_]; try destruct n1;`
or
`destruct a1 as [n1|_|_ _|_ _|_ _]; try destruct n1;`
gave
`Error: _ is used in conclusion.`

But
`destruct a1 as [n1|?|?|?|?]; try destruct n1;`,
you suggested, works well.

**Comment by jeehoonkang** [comment]
Ah, `||` is interpreted as `Prop`ositional OR. You should give a space like: `[| |]`.

Jeehoon

**Comment by jaewooklee93** [comment]
Thank you. I think `[n1|?|?|?|?]` is preferable, since it may be the most readable.
