### ISSUE TITLE
About symbols for case analysis

### ISSUE THREAD

**Issue by jaewooklee93** [snu-sf/pl2015#103]
For this week's assignment, I use more than three levels of case analysis and I'm running out of symbols. For the depth<4, of course, I used `-, +, *`, but after that what can I use? I know `{` works as well, but they need to be closed by `}`, so it is cumbersome to use and not pretty, too...

**Comment by jaewooklee93** [comment]
Well, if I use `{` as outermost case, I don't need to close them for so many times.

**Comment by jeehoonkang** [comment]
If you enclose script by `{ }`, you can use `- + *` once more. I structure proof like this:

```
- ...
  + ...
    * ...
      { ...
        - ...
      }
```

**Comment by jaewooklee93** [comment]
But if I have to write many cases with depth 4 (not 5), Is the only way the following?

``` Coq
- ...
  + ...
    * ...
      { ...
      }
      { ...
      }
      { ...
      }
      { ...
      }
      ...
```

**Comment by jeehoonkang** [comment]
Unfortunately, yes..

but that deep depth smells the need of sublemmas, said the Coq developers..
