### ISSUE TITLE
GitHub Repository Status

### ISSUE THREAD

**Issue by jeehoonkang** [snu-sf/pl2015#11]
- Please add me (@jeehoonkang) as a collaborator.
  @backspe @bsantosb @chlehd0509 @dmsqlcejtk @dyoum117 @egejjespersen @hexagonaled @kanggyu94 @pakhyunghoon @wonheejo 
- Please make repository private
  @2013-11390 @201313381lmk @adambj @amityaffliction @anna-feliz @aritaum55 @backspe @blinkingstar7 @bsantosb @chlehd0509 @cocghe210 @dmsqlcejtk @donk0501 @dukeow94 @dyoum117 @egejjespersen @gglns94 @hexagonaled @hiayuna @hyeongmee @hyeongook @hyunjin95 @int-her @jaewooklee93 @justlaugh05 @jyon @kanggyu94 @kedia94 @ksh931102 @kyeongmoonkim @leedongkwon @leegyeonggeon @luke9407 @minitu @pakhyunghoon @qkr0990 @r4ddek @raysuhyunlee @reasonably @rhs0266 @sanha @solrefa @sungmincho @winimus @wonheejo @woong8556 @ysm1180  
  I know some of you are not getting free repositories from GitHub. Please discuss the issue here: https://github.com/snu-sf/pl2015/issues/7
- Those who did everything good
  @alkaza @amoretspero @artberryx @ch7457 @dormant09 @fortunist @gonggit @ik1ne @jonggwon @ksami @lebeny @nahj135 @ntopia @parkdaeyoung @raifthenerd @renios @sangholee12 @sanghoon-park-snu @sophiechoi @treenson @whoknowwhat @wonook @yujunkim @yulcat 
  Good job!

Jeehoon

**Comment by anna-feliz** [comment]
Hello!

My github is anna-feliz, and my student number is 2015-81468, what should I
do to connect these two?

Regards
Anna
Den 10 mar 2015 20:34 skrev "Jeehoon Kang" notifications@github.com:

**Comment by alkaza** [comment]
Dear Jeehoon Kang,

I am Alena Kazakova @alkaza https://github.com/alkaza 2013-11409

I think my repository is private now, could you please check?

Thank you,

Alena Kazakova

**Comment by jeehoonkang** [comment]
@anna-feliz I will connect it. Thanks!

**Comment by jeehoonkang** [comment]
@alkaza I don't think so. If your repository https://github.com/alkaza/pl2015 is private, than there will be a `PRIVATE` tag next to the repository name..

**Comment by alkaza** [comment]
Sorry, then I cannot make it private yet.
I searched for how to make a public repository private
https://help.github.com/articles/making-a-public-repository-private/ and it
seems like I still cannot do it for free

**Comment by jeehoonkang** [comment]
@alkaza Did your application for student program granted?

For me, https://education.github.com/discount_requests/new says something like:

```
You have submitted 1 request:
    Sep 14, 2014 for @jeehoonkang – Approved
```

Jeehoon

**Comment by Reasonably** [comment]
안녕하세요 조교님
제가 2013-11397이고 @Reasonably입니다 ㄷㄷ 구글독스 제출안해서 혼란을 드린점 정말 죄송합니다 ㅠㅠ

**Comment by alkaza** [comment]
It says

You have submitted 1 request:
- Mar 5, 2015 for @alkaza https://github.com/alkaza – _Pending_

**Comment by jeehoonkang** [comment]
@Reasonably Ok Thanks!

**Comment by jeehoonkang** [comment]
@alkaza I asked GitHub team to give you discount sooner. Wait a little bit more, please. Sorry.

**Comment by renios** [comment]
안녕하세요. 

github name renios, 2009-12801 김민정 입니다.

월요일(9일)에 https://github.com/snu-sf/pl2015/blob/master/copy-repository.sh https://github.com/snu-sf/pl2015/blob/master/copy-repository.sh 에 올려주신대로 copy했고,
메일을 받은 후 다시 확인해보았지만 동일하게 아래와 같은 상황입니다.

copy가 되지 않았다면 저 log가 나올 수 있는 것인가요?

감사합니다.

**Comment by jeehoonkang** [comment]
@renios My https://github.com/renios/pl2015 give me `Page not found`..
- Did you make it private?
- Then would you please add me as a collaborator? https://help.github.com/articles/adding-collaborators-to-a-personal-repository/

**Comment by renios** [comment]
늦은시간까지 도움 감사드립니다.

다음과 같이 collaborator 추가하였습니다.

**Comment by jeehoonkang** [comment]
@renios ack

**Comment by jeehoonkang** [comment]
@amoretspero
- I cannot see https://github.com/amoretspero/pl2015
- Did you make me a collaborator? https://help.github.com/articles/adding-collaborators-to-a-personal-repository/

**Comment by amoretspero** [comment]
Oh, I forgot to make you collaborator. I did it just a minute ago. After making you the collaborator of repository pl2015, is it all done??

**Comment by jeehoonkang** [comment]
@amoretspero ack

**Comment by Parkdaeyoung** [comment]
I got discount request approved and made my repository private. Please check.

**Comment by ntopia** [comment]
I made my repository private too.

**Comment by jeehoonkang** [comment]
@Parkdaeyoung @ntopia ack

**Comment by alkaza** [comment]
My request got approved, too. It is private now.

**Comment by AdamBJ** [comment]
I'm still waiting for mine, as of today at 3:00pm it's:

You have submitted 1 request:
Mar 5, 2015 for @AdamBJ – Pending

**Comment by amityaffliction** [comment]
My request got approved, i made it private now.

**Comment by HexagonalED** [comment]
I've sent email twice to github, after verifying my account with snu email.. but still, Github is not responding. :(

**Comment by HexagonalED** [comment]
Oh, Never mind. I was foolish.

**Comment by LeeGyeongGeon** [comment]
I submitted request but I think GitHub would not give me a private repositry..

**Comment by rhs0266** [comment]
My discount request is rejected.

**Comment by jeehoonkang** [comment]
@LeeGyeongGeon @rhs0266 That's strange..
Would you please come to 301-554-2 at the office hour?

Jeehoon

**Comment by r4ddek** [comment]
Just made it private! Thanks!

**Comment by quan6791** [comment]
check my repository!thank you!
