### ISSUE TITLE
Request of Assignment Status by TA

### ISSUE THREAD

**Issue by egejjespersen** [snu-sf/pl2015#114]
Hi, Jeehoon Kang!

@jeehoonkang. 
I'd like to hear if you've had any problems correcting my assignments? I remember being CC'ed in an issue where you had some problem with my Assignment03, but I haven't heard anything from you, since I wrote you back on that topic.

Please write me a personal message on " egejjespersen@gmail.com ", and let me know all my assignments have been submitted satisfactory.

Kind regards,
Ege

**Comment by jeehoonkang** [comment]
I replied your email. I will process ASAP. Jeehoon
