### ISSUE TITLE
When occured the error "Protocol https not supported or disabled in libcurl" while copying snu-sf/pl2015.git

### ISSUE THREAD

**Issue by chlehd0509** [snu-sf/pl2015#12]
This error is caused by referring 'libcurl.dll' in C:\Windows\SysWOW64.
So You should change 'libcurl.dll' in C:\Windows\SysWOW64 with 'libcurl.dll' in C:\Users[$USERNAME]\AppData\Local\GitHub.
I would be of help to you in using Github.

**Comment by jeehoonkang** [comment]
Nice tip! thank you.
