### ISSUE TITLE
Can't solve Assignment09_05: don't know how to use hoare_if...

### ISSUE THREAD

**Issue by ik1ne** [snu-sf/pl2015#129]
I managed to solve 09_05, but I didn't used `hoare_if`(with definition of 09_00).
And I think it is the worst way to prove 09_05.
In fact, I don't know how to use `Theorem hoare_if` in assignment file.
Can you give me a hint, or an example by proving `Example if_example` in Hoare.v? (using `hoare_if` from Assignment09_00.v, since there is already a proof using `Theorem hoare_if` from Hoare.v)

**Comment by jaewooklee93** [comment]
#123 #124

**Comment by ik1ne** [comment]
@jaewooklee93 Thank you! I've read #123, but haven't read #124 since it was closed before I check it, so I thought nobody was asking for it.

**Comment by alkaza** [comment]
Does anyone know why ```apply hoare_if.``` works as a first step of proving ```Theorem if_minus_plus``` in ```Hoare.v``` but doesn't work in ```Assignment09_05```? I proved it in the chapter file, but the proof doesn't work in the assignment file. 

For some reason in the assignment file I have:
```
1 subgoals
______________________________________(1/1)
{{fun _ : state => True}}
IFB BLe (AId X) (AId Y) THEN Z ::= AMinus (AId Y) (AId X)
ELSE Y ::= APlus (AId X) (AId Z) FI {{fun st : state => st Y = st X + st Z}}
```

When in the chapter file it looks like:
```
1 subgoals
______________________________________(1/1)
{{fun _ : state => True}}
IFB BLe (AId X) (AId Y) THEN Z ::= AMinus (AId Y) (AId X)
ELSE Y ::= APlus (AId X) (AId Z) FI {{fun st : state => st Y = st X + st Z}}
```

Why is it different?

**Comment by alkaza** [comment]
Does anyone know why ```apply hoare_if.``` works as a first step of proving ```Theorem if_minus_plus``` in ```Hoare.v``` but doesn't work in ```Assignment09_05```? I proved it in the chapter file, but the proof doesn't work in the assignment file.
