### ISSUE TITLE
Poll on Final Exam

### ISSUE THREAD

**Issue by jeehoonkang** [snu-sf/pl2015#130]
Hi all,

I prepared a poll for final exam: http://doodle.com/x4nz8qifichb4czn
Please answer before 6/4 (Thu).

Jeehoon

**Comment by minitu** [comment]
I think 2 dates are missing on the poll: Fri 19 and Sat 20.

**Comment by jeehoonkang** [comment]
@minitu That's intentional. Gil and I cannot host the final exam on those days.

Jeehoon

**Comment by alkaza** [comment]
I think at the time when most students voted they didn't know that the Algorithms exam is going to be on 18th. I know half of the students in this class are taking Algorithms. Please consider it when voting, having two hard exams at the same day is not nice...

**Comment by jeehoonkang** [comment]
As discussed in the class, the final will be held at:
- 6/18 (Thu) 18:00-21:00
- Software Lab, 3rd floor, Bldg 301
