### ISSUE TITLE
reverse of multi_R in context

### ISSUE THREAD

**Issue by AdamBJ** [snu-sf/pl2015#138]
```
1 subgoals
t1 : tm
t2 : tm
t2' : tm
H : value t1
H0 : t2 ==>* t2'
______________________________________(1/1)
t2 ==> t2'
```

I want to apply the reverse of multi_R to H0 in the context, does something like that exist?

**Comment by jaewooklee93** [comment]
No, I think it's impossible. There is a case `t2 = t2'`  (#step = 0) under the condition of `t2 ==>* t2'` (#step ∈ Nat) , but then `t2 ==> t2'` (#step = 1) cannot be true.

**Comment by AdamBJ** [comment]
Ok, I'll stick with induction for that question then, thanks.
