### ISSUE TITLE
Class canceled: 2nd June

### ISSUE THREAD

**Issue by jeehoonkang** [snu-sf/pl2015#139]
Tomorrow(2nd June)'s class is canceled.

Jeehoon

**Comment by AdamBJ** [comment]
Given that we had no lecture on Tuesday, would Professor Hur consider narrowing the scope of the course by one or two chapters, or giving us a break on some of the homework? I feel like going all the way up to References now really puts a big burden on students as it's such a huge amount of material to cover in such a short time. In my case, I'm spending more than double the amount of time studying for this class than I'm spending on any of my other CS classes, and consequently I feel like my performance in my other classes is suffering. I'd really appreciate it if Professor Hur would lighten the load a little bit, and I'm sure many other students feel the same way.

**Comment by alkaza** [comment]
I completely agree with @AdamBJ, this class takes more time than any other class...

**Comment by jeehoonkang** [comment]
@AdamBJ @alkaza I discussed on this matter with Professor Hur, and he said he will manage the course load properly.

Jeehoon
