### ISSUE TITLE
GitHub Repository Status

### ISSUE THREAD

**Issue by jeehoonkang** [snu-sf/pl2015#14]
- Please make repository private. (DONE)
  - Make sure you have a verified `@snu.ac.kr` email address (https://help.github.com/articles/verifying-your-email-address/).
  - A student reported that he received the verification email in spambox. Please check!
  - At GitHub education page (http://education.github.com/), "Request a discount" with `@snu.ac.kr` email address.
  - Contact GitHub at https://education.github.com/contact and send a message as follows.

```
Subject: Request for Faster Transaction for Course
Content:
Hi GitHub Education Team,
I am YOURNAME, a student from Seoul National University.

This semester I take Programming Languages course, 
and to attend the the course, I have to prepare for a private repository.

So I applied a discount from education.github.com, but I could not get an approval.
As the first assignment will be issued next week, I will need a free repository soon.

So may I ask if you could approve my application sooner than usual?
My TA (@jeehoonkang) said he asked Mr. Sanicki (@sanicki) to help me, so I contacted via this channel.

Thanks,
YOURNAME
```

**Comment by gyu-kang** [comment]
Adding collaborator, Making repository as private
모두 다 했습니다! 확인 부탁드려요.

**Comment by skwn-j** [comment]
Hi Seokwon,

Your application was rejected for not including proof of enrollment. You must add your school email to your GitHub account and apply again.

Cheers,
Scott

Got this mail, so I requested it again. Please wait more time.

**Comment by jeehoonkang** [comment]
@winimus Please come to my office as soon as possible tomorrow.

Jeehoon

**Comment by LeeGyeongGeon** [comment]
I did make my repo private.

**Comment by bsantosb** [comment]
My repo is private already.

**Comment by jeehoonkang** [comment]
Thank you for your cooperations. I just updated the status.

**Comment by woong8556** [comment]
Mine's also private.

**Comment by jeehoonkang** [comment]
@alimkim @backspe @blinkingstar7 @dukeow94 @gglns94 @hexagonaled @hyeongmee @raysuhyunlee @rhs0266 @winimus @wonheejo 

I would like you to come to my office (301-554-1) next Monday 13:00-15:00, Tuesday 13:00-17:00 18:15-20:00.
I would like to figure out why your applications for student discount is delayed, and you could not make your repositories private.

Jeehoon

**Comment by raysuhyunlee** [comment]
Hello! Please ignore my repository since I'm going to drop this class. Sorry for the confusion!

**Comment by jeehoonkang** [comment]
@RaySuhyunLee Sad to know :sob: Wish you the best!

Jeehoon

**Comment by HexagonalED** [comment]
I've sent my request at your presence(I remember the time as 3/16 2 o'clock), but still, it is pending. So, I think I have to wait until the request is rejected.

**Comment by jeehoonkang** [comment]
@HexagonalED @gglns94 @rhs0266 @Backspe @BlinkingStar7 @dukeow94 I would like to know your status on private repos :-)

Jeehoon

**Comment by rhs0266** [comment]
Still pending...

**Comment by jeehoonkang** [comment]
@rhs0266 Would you please make sure that you requested with an `@snu.ac.kr` email address? Thanks.

Jeehoon

**Comment by Backspe** [comment]
I dropped this class.
