### ISSUE TITLE
Some problems in the first assignment.

### ISSUE THREAD

**Issue by ghost** [snu-sf/pl2015#18]
The exercise named `blt_nat` is given as:

```
(** The [blt_nat] function tests [nat]ural numbers for [l]ess-[t]han,
    yielding a [b]oolean.  Instead of making up a new [Fixpoint] for
    this one, define it in terms of a previously defined function.  

    Note: If you have trouble with the [simpl] tactic, try using
    [compute], which is like [simpl] on steroids.  However, there is a
    simple, elegant solution for which [simpl] suffices. *)
```

But I think that no proper functions are defined in the `Assignment01.v` :(

**Comment by jeehoonkang** [comment]
You mean, there is no `previously defined function`?

Jeehoon

**Comment by ghost** [comment]
Yes, that's what i mean.

**Comment by ntopia** [comment]
I have a similar question.
Should we do homework using functions defined in 'Assignment01.v' only?

**Comment by jeehoonkang** [comment]
Please ignore the direction: `define it in terms of a previously defined function`.
Define `blt_nat` with a `Fixpoint`.

Jeehoon

**Comment by liveseongho** [comment]
We must define blt_nat with Fixpoint? or can we make some other function with Fixpoint and use it to blt_nat?

**Comment by jeehoonkang** [comment]
@ch7457 Define `blt_nat` with a `Fixpoint`.

**Comment by jeehoonkang** [comment]
@ch7457 You defined `ble_nat` with `Fixpoint` and use it to define `blt_nat`. I think that is good, too.

Jeehoon
