### ISSUE TITLE
How can I check whether I pushed my assignment? Can TA pull my repository only if I answer his pulling request?

### ISSUE THREAD

**Issue by 201313381lmk** [snu-sf/pl2015#19]
Is the pushing successful if I can see my commit on GitHub website? And what is 'pulling request'? Can TA pull my repository only if I answer his pulling request?

**Comment by jeehoonkang** [comment]
- I looked at your repo, and I think you successfully submitted your answers.
- In this course, you don't need to care about pull requests. It is a feature that helps you to do inter-repository copy.
- Just make sure that I can _see_ your repo. Also, make sure to make your repo private.

Jeehoon

**Comment by liveseongho** [comment]
I pushed my complete Assignment01.v too. But I'm not sure I've pushed successfully. Can you check my repo too?

**Comment by jeehoonkang** [comment]
@ch7457 your repo looks good to me.

**Comment by rhs0266** [comment]
github.com/rhs0266/pl2015에 제대로 업로드 된거면 push가 제대로 된것인가요?

**Comment by LeeGyeongGeon** [comment]
@jeehoonkang I tried to push my Assignment01.v in my private repo. And I found there's Assignment01.v in my repo. Then, can I think I submitted well?

**Comment by jeehoonkang** [comment]
@rhs0266  LGTM

**Comment by jeehoonkang** [comment]
@LeeGyeongGeon LGTM

**Comment by alkaza** [comment]
Could you please check my repo as well, since it's the first assignment?
Thank you!

**Comment by jeehoonkang** [comment]
@alkaza LGTM
