### ISSUE TITLE
makefile update issue

### ISSUE THREAD

**Issue by yujunkim** [snu-sf/pl2015#20]
In [homework.md#submission](https://github.com/snu-sf/pl2015/blob/master/Homework.md#submission)
 `Make sure your source code is compiled without error before submission. TA will compile by make clean; make in Linux environment. This should not fail.`

So I think `Assignment01.v` should be list of `VFILES` in `Makefile` like [this](https://github.com/yujunkim/pl2015/blob/ecc90a8962430e7ef642755f663550e73a43c807/sf/Makefile)

Or, do I have to update `Makefile` every Assignment?

**Comment by jeehoonkang** [comment]
Ah, I forgot to update `Makefile`. For assignment 1, please leave `Makefile`. Just make sure that `Assignment01.v` is compiled without errors.

**Comment by yujunkim** [comment]
Thanks!

**Comment by jeehoonkang** [comment]
If you don't mind, I would like to keep it till the due of Assignment 1. Is it OK?

**Comment by yujunkim** [comment]
Of course. Reopen this?
