### ISSUE TITLE
Is there any recommendable editor for Coq?

### ISSUE THREAD

**Issue by fortunist** [snu-sf/pl2015#22]
It seems that CoqIDE is very inconvenient to use for editing coq files. (ex : not support auto-indent)
I found an eclipse plugin named coqoon, but it does not work properly.
Could you recommend any coq editor which has auto-indent, syntax coloring, coqIDE plugin, etc? (except Vim, for windows...)

**Comment by jeehoonkang** [comment]
I personally use ProofGeneral on Emacs: http://proofgeneral.inf.ed.ac.uk/

**Comment by alkaza** [comment]
Does the professor use ProofGeneral as well?

**Comment by jeehoonkang** [comment]
@alkaza Yes.

**Comment by ksami** [comment]
I've found a plugin for Sublime Text but it has a few bugs on Windows. If you're interested I can send you the files once I've patched it for Windows.

**Comment by whoknowwhat** [comment]
[Coq.vim](https://github.com/jvoorhis/coq.vim) and [coquille](https://github.com/the-lambda-church/coquille) are nice combination for Vim.
