### ISSUE TITLE
Problems with Induction.v (Line 378)

### ISSUE THREAD

**Issue by alkaza** [snu-sf/pl2015#26]
In the Induction.v file, on line 378, there is an exercise:

```
(** **** Exercise: 2 stars, optional (evenb_n__oddb_Sn)  *)

(** Prove the following simple fact: *)

Theorem evenb_n__oddb_Sn : forall n : nat,
  __evenb__ n = negb (evenb (S n)).
Proof.
  (* FILL IN HERE *) Admitted.
(** [] *)
```

which gives an error message: 

```
Error: The reference evenb was not found in the current environment.
```

Wasn't evenb supposed to be defined? 

The file does not compile:

```
Error: The reference evenb was not found in the current environment.Compilation output:
File "C:\Users\Alena\GitHub\pl2015\sf\Induction.v", line 378, characters 2-7:

Error: The reference evenb was not found in the current environment.
```

**Comment by jeehoonkang** [comment]
`evenb` is defined in `Basics.v`, so you have to compile it before using `evenb` in `Induction.v`. a `make` command will solve this problem, I think.

Jeehoon

**Comment by alkaza** [comment]
I compiled the Basics.v but the error does not go away.
I think evenb it is not defined in it.

**Comment by jeehoonkang** [comment]
Doesn't your `Basics.v` contain:

```
Fixpoint evenb (n:nat) : bool :=
  match n with
  | O        => true
  | S O      => false
  | S (S n') => evenb n'
  end.

```

?

**Comment by alkaza** [comment]
Sorry, checked the original file and it is defined. I think I might have
deleted it accidentally.

**Comment by alkaza** [comment]
I found out that i had a compilation problem. Whenever i do Make, my coqIDE
crushes. What should I do?

**Comment by jeehoonkang** [comment]
I recall someone else complained about the same problem. Would anybody please share more stories for this issue? Thanks.

**Comment by jeehoonkang** [comment]
It turns out that if you don't have `make`, then CoqIDE crashes if you command `make` inside CoqIDE. That's strange, but installing `make` solved the problem.

Jeehoon

**Comment by alkaza** [comment]
Thank you!!!
