### ISSUE TITLE
Problems in Lists.v

### ISSUE THREAD

**Issue by liveseongho** [snu-sf/pl2015#27]
There's an error when I progress "Require Export Induction."

Error: Compiled library Induction.vo makes inconsistent assumptions over
library Coq.Init.Notations

How can I solve this?

**Comment by jeehoonkang** [comment]
Would you please try `make clean` and then `make`?

**Comment by liveseongho** [comment]
I did. But still doesn't work.
Same error message.

**Comment by jeehoonkang** [comment]
That's most strange.. Would you please come to my office tomorrow before 3:20, or next week? Thank you.

Jeehoon

**Comment by jeehoonkang** [comment]
That's most strange.. Would you please come to my office tomorrow before 3:20, or next week? Thank you.

Jeehoon

**Comment by liveseongho** [comment]
OK, I'll drop by next week. Thank you.

**Comment by jeehoonkang** [comment]
I recall this problem is resolved. If not, please let me know :-)
