### ISSUE TITLE
Compile about submission 

### ISSUE THREAD

**Issue by gyu-kang** [snu-sf/pl2015#28]
In homework.md,
Make sure your source code is compiled without error before submission. TA will compile by make clean; make in Linux environment. This should not fail.

I pushed assignment01.v without compiling...
But, the above sentence in homework.md says that TA compiles my code when checking my homework.
1. Is it okay to upload .v file only or should I upload assignment01.v and another files created at compiling?
2. How can i run and check compiled one, to see if it's running correct?

**Comment by jeehoonkang** [comment]
Coq source file is enough.

**Comment by jeehoonkang** [comment]
Fir assignment 1, just it was enough to check if Coq script runs well in coqide. From assignment 2, I will specify how to check compilation.

Jeehoon

**Comment by gyu-kang** [comment]
Thank you!

**Comment by jeehoonkang** [comment]
For assignment 02, just push `Assignment_02.v` and make sure that compiles well. (as assignment 01)

Jeehoon
