### ISSUE TITLE
Question about my mistake.

### ISSUE THREAD

**Issue by Parkdaeyoung** [snu-sf/pl2015#32]
Sorry for the Q about the mistake I made in merging the assignment2. 
In brief, I removed "Assignment_1.v" file using "git rm sf/Assignment_1.v" command a minute ago and pushed my local repository(which has no ass1) to the remote. So, If you visit my remote repository, you'll notice that my "Assignment_1.v" file has been uploaded a few minute ago becauase I pushed again with the file.
Actually, I had pushed Ass1 to the remote before the due date so that if you fetched my repo at due time(hopefully), I guess it's no big deal. 
Is there any problem with this? Thank you!

**Comment by jeehoonkang** [comment]
Hi @Parkdaeyoung. I already pulled your submission at the due time, and your submission LGTM.

Jeehoon

**Comment by Parkdaeyoung** [comment]
Thank you!
