### ISSUE TITLE
Question about Assignment 2

### ISSUE THREAD

**Issue by jaewooklee93** [snu-sf/pl2015#33]
I think some comments given in the Assignment 2 are somewhat misleading.
For example, 

``` Coq
(** **** Problem #7 : 4 stars (mult_comm) *)
(** Use [assert] to help prove this theorem if necessary.  
    You shouldn't need to use induction. *)

Theorem plus_swap : forall n m p : nat, 

(** **** Problem #8 : 3 stars (mult_comm) *)
```

Those comments refer to `mult_comm`, even though there is no theorem named `mult_comm` in the whole assignment.

**Comment by jeehoonkang** [comment]
e59aee9eb6771b953b01534faea885dccc445681

**Comment by jaewooklee93** [comment]
Thank you.

But still I am unable to find `mult_comm` even though

```
(** **** Problem #8 : 3 stars (mult_comm) *)
```

remains yet.

Is `mult_comm` intentionally excluded?

**Comment by jeehoonkang** [comment]
Hi! I think labels there are not important, and `mult_comm` is included by mistake. Please solve the question as stated in code (not comment)!

Jeehoon
