### ISSUE TITLE
How can I recover a deleted assignment file?

### ISSUE THREAD

**Issue by jaewooklee93** [snu-sf/pl2015#35]
It can be a silly question, but after I directly removed Assignment_02.v file in my computer, I cannot download it again from snu-sf/pl2015 via fetch-homework.sh file. Does that script operate only once? I'd like to get "clean" files from snu-sf/pl2015.

**Comment by jeehoonkang** [comment]
`git status` and then make sure `git checkout sf/Assignment_02.v` will restore the original file.

And read try.github.io

Jeehoon

**Comment by jaewooklee93** [comment]
Thank you, but `git checkout sf/Assignment_02.v` only gave the following.

```
error: pathspec 'sf/Assignment_02.v' did not match any file(s) known to git.
```

I also couldn't see that file at `git status`.

I tried several hundreds of git commands, but `Assignment_02.v` has never come back. :(

**Comment by jeehoonkang** [comment]
I would like you to tar/zip your repo and then send me via email.

Jeehoon

**Comment by jeehoonkang** [comment]
The problem occurred because you committed to remove the file.
You have to revert the commit that removes that file by `git revert [commit hash]`.

**Comment by jaewooklee93** [comment]
Thank you. `git revert` works pretty well.
