### ISSUE TITLE
How can I maintain my parentheses?

### ISSUE THREAD

**Issue by LeeGyeongGeon** [snu-sf/pl2015#38]
![image](https://cloud.githubusercontent.com/assets/11293091/6796622/efeb6234-d239-11e4-9dbc-39dc564503b1.png)

I'm so stressful because Coq is deleting my parentheses. I tried to maintain my parentheses but everytime I try Coq delete those! Can you help me about this?

**Comment by jeehoonkang** [comment]
I am not quite sure which problem you are troubling with; would you please come to 301-554 today no later than 20:00?

Jeehoon

**Comment by jaewooklee93** [comment]
I think it's a natural thing. Because + operator has left associativity, there is no need to write (a+b)+c, and a+b+c is just okay. I guess that coq did it automatically for neat viewing.

**Comment by jeehoonkang** [comment]
BTW try to focus on the lecture right now :-)

Jeehoon

**Comment by LeeGyeongGeon** [comment]
@jeehoonkang  Well.. I found some way to accommodate with this phenomenon. Thank you!
