### ISSUE TITLE
Can I use "auto." while solving problem?

### ISSUE THREAD

**Issue by Kedia94** [snu-sf/pl2015#39]
I found that using "auto." is easy way to proof.
Is there any penalty if I use auto in assignment?

**Comment by jeehoonkang** [comment]
- I don't think so. Use tactics as you wish.
- However, it would be helpful to understand the intent of software foundations authors not to use `auto` at the beginning of the book. You may find later assignments hard if you are addicted with `auto` at the beginning.

Jeehoon
