### ISSUE TITLE
Please copy this repository

### ISSUE THREAD

**Issue by jeehoonkang** [snu-sf/pl2015#4]
@LeeGyeongGeon @snu-amoretspero @cocghe210 @egejjespersen @jwlee93 @reinos

Hi!
- I cloned everyone's repositories, and I realized that you did not create a repository, give me an access permission, nor copy this repository into yours.
- Please copy this repository and give me an access, and then let me know no later than Tuesday 17:00.
- If you have a question, feel free to ask!

Jeehoon

**Comment by egejjespersen** [comment]
Yo!

I really have no idea how to that.

//Ege

**Comment by jeehoonkang** [comment]
Hi @egejjespersen !
- Download this [script](https://github.com/snu-sf/pl2015/blob/master/copy-repository.sh).
- Run a terminal. If you are using Windows, install [Git for Windows](http://git-scm.com/download/win), and then run "git bash".
- Run `USERID=egejjespersen WORKSPACE=~ ./copy-repository.sh`
- Then GitHub's your repository will be filled with this repository's contents, and you will have `~/pl2015` directory for you to work on.

Jeehoon

**Comment by quan6791** [comment]
![erros](https://cloud.githubusercontent.com/assets/6868702/6540635/1113954a-c4ec-11e4-9637-0bd8e2824810.png)
this is my error

**Comment by quan6791** [comment]
![erros](https://cloud.githubusercontent.com/assets/6868702/6540663/1749a2c2-c4ee-11e4-8a77-10f0b181579e.png)
Then now this becomes this problem when I created the pl2015 repository

Quan

**Comment by jeehoonkang** [comment]
Hi @cocghe210 ,
- I think you successfully copied: https://github.com/cocghe210/pl2015
- Do you have any remaining problem now?

Jeehoon

**Comment by quan6791** [comment]
thank you , my problem is solved. But I still cannot push my file to the repository when I tried to type:
git push origin master , this thing happened

![erros](https://cloud.githubusercontent.com/assets/6868702/6541048/d5ca0b3a-c500-11e4-83ab-0f6838213768.png)

**Comment by jeehoonkang** [comment]
@cocghe210 

As you can see, your command:

```
git remote add origin https://github.com/cocghe210/pl2015.git
```

gives you an error message:

```
fatal: remote origin already exists.
```

This is because you didn't:

```
git remote rm origin
```

So your `origin` branch is still `github.com/snu-sf/pl2015.git`, to which you don't have permission to push. Read the script once more, and follow the instruction as-is one more time.

Jeehoon

**Comment by quan6791** [comment]
Ok , I see. Thank you

**Comment by egejjespersen** [comment]
Hello, Again!

I don't know if I have done it correctly. Here's what it says:

Regards,
Ege

**Comment by jeehoonkang** [comment]
@egejjespersen I am afraid I could not understand what you said. Would you please repeat?

Jeehoon

**Comment by egejjespersen** [comment]
Have I done it correctly? Have I created a repository or copied the
repository into mine?

//Ege

**Comment by jeehoonkang** [comment]
@egejjespersen No, your repository is empty: https://github.com/egejjespersen/pl2015
- Have you executed the script?
- BTW I could not understand the "Here's what it says:" part.

**Comment by jeehoonkang** [comment]
I checked that @cocghe210 @LeeGyeongGeon did copy the repository.

**Comment by jeehoonkang** [comment]
@HexagonalED @dyoum117 @jyon @wonheejo

I just realised that you guys also did not copy the repository properly.
Please follow the manual here :)

**Comment by HexagonalED** [comment]
Hi! I've just tried to copy the repo by following the manual, but it comes with an error : 

error: failed to push some refs to 'https://github.com/HexagonalED/pl2015.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

how can i solve it?

and also, after copying, still can I work(commit or do anything else) just like the same way i work in my private repo?

thanks.

**Comment by jeehoonkang** [comment]
@HexagonalED this is because you already have a repository not compatible with this repo. First delete your repo, recreate WITHOUT README, and try again.

Jeehoon

**Comment by LeeGyeongGeon** [comment]
Actually, I made a repository and added you as a collaborator

![image](https://cloud.githubusercontent.com/assets/11293091/6569747/0e00cbe0-c733-11e4-851b-739ee4ab54e7.png)

![image](https://cloud.githubusercontent.com/assets/11293091/6569752/1f948266-c733-11e4-8e03-05a6a40224b8.png)

What's the problem?

**Comment by LeeGyeongGeon** [comment]
I couldn't make it private. It can be a problem? But I didn't receive any private repository from GitHub

**Comment by jeehoonkang** [comment]
Hi @LeeGyeongGeon !
- "I checked that @cocghe210 @LeeGyeongGeon did copy the repository." Thank you for your cooperation!
- Yes you have to make it private, to prevent other students from seeing your source code.
- Did you apply for GitHub Education program? https://education.github.com/

**Comment by jeehoonkang** [comment]
@renios

**Comment by wonheejo** [comment]
i have no idea whats to be done....could i get help tomorrow during the session at 8:30?

**Comment by jeehoonkang** [comment]
@wonheejo Obviously. Come to 302 3rd floor Software Lab.

Jeehoon

**Comment by wonheejo** [comment]
감사합니다 ㅜㅠ

**Comment by amoretspero** [comment]
I have mailed to "pl2015@sf.snu.ac.kr" that there was some problem with my ID 'snu-amoretspero' so that instead of that ID, I will use 'amoretspero'. I have copied pl2015 repository and made it private. Please check!

**Comment by wonheejo** [comment]
i tried copying the repository on my own...and i got stuck on this point....

![2015-03-12 11 25 20](https://cloud.githubusercontent.com/assets/11328403/6611057/a0a4f958-c8aa-11e4-8295-37e3fae42ac8.png)

**Comment by jaewooklee93** [comment]
Although it is quite old issue, i want to inform you that I've never used the account jwlee93, since it is not associated with my school mail address.
