### ISSUE TITLE
Coq Ide 'Save failed' problem.

### ISSUE THREAD

**Issue by aritaum55** [snu-sf/pl2015#40]
when I create new coq file and try to save it, A Message -save failed- is printed.

I don't know why it happens.
could you help me solving this problem?

**Comment by jeehoonkang** [comment]
I am not aware of the problem, but I have a gut feeling that your hard disk may not have enough space. Would you please check for it first?

**Comment by jeehoonkang** [comment]
Any progress on this issue?

**Comment by aritaum55** [comment]
I solved this problem. the problem was directory name that was written in korean
