### ISSUE TITLE
On merging

### ISSUE THREAD

**Issue by Parkdaeyoung** [snu-sf/pl2015#44]
Hello. I have question about git 'fetch and merge'.
Whenever I try to execute the fetch script you loaded and pull a new assignment, it changes my files, specifically, the last assignment. I think the 'merge' command has something to do with it. 
Is there any way to keep local files unmodified after pulling a new assignment? Is there no problem with that but me? I want to know what I am missing.
Expecting an insight on it, Thanks.

**Comment by jeehoonkang** [comment]
- I guess you added `Assignment03.v` before fetching and applying. Right?
- In that case, you are inherently obliged to do merge. So from now on, try to fetch and apply commits before adding `Assignment03.v` on your own.
- You can merge by modifying `assignment03.v` and comitting (`git commit`). Your commit and the official commit on assignments are inherently different, so merge is inevitable.

Jeehoon

**Comment by ksami** [comment]
The git command `git merge -s ours` favours commits made by, in this case, students. Perhaps this could be added into the fetch homework script instead?

Source: http://git-scm.com/docs/git-merge

**Comment by jeehoonkang** [comment]
@ksami I am not sure that is a good idea, in our purposes. For many cases, it would be more reasonable to favor official commits than students' commits. I would like to let students to choose how to merge in these cases on their own.

Jeehoon

**Comment by ksami** [comment]
That's true. I just think it might be difficult for those new to git to understand merging.

**Comment by Parkdaeyoung** [comment]
It's very complicated for me but I can see your point. thanks a lot!
