### ISSUE TITLE
Midterm Exam

### ISSUE THREAD

**Issue by alkaza** [snu-sf/pl2015#47]
When are we going to have a midterm exam? And will we have to use lab's computers and submit the exam file to github repository?

**Comment by jeehoonkang** [comment]
- Mid-term will be at 4/28 or 4/30. We will decide later.
- Final will be at 6/13.
- Exams will be from 17:00-19:00.
- Procedure for submission and evaluation will be announced later.

Jeehoon

**Comment by wonook** [comment]
6/13 is a Saturday. Is this a fixed date?

**Comment by gilhur** [comment]
Yes, the final exam date is fixed unless there is a good reason to change it.

**Comment by jaewooklee93** [comment]
I think I heard that midterm is on 4/23. Is it right?

Also, professor said that we cannot use `omega.` tactic in the exam.
Is there any other restriction? How about `auto.`? I've never experienced the case that `auto.` did something useful for me, though.

**Comment by alkaza** [comment]
Which topics are going to be covered in the exam?

**Comment by gilhur** [comment]
Oops. I made a mistake about the midterm exam date in the last class.
The midter exam is on 4/30 (Thursday).
I will fix this in the next class.

**Comment by alkaza** [comment]
Thank you! That was our question after the last class!

**Comment by amityaffliction** [comment]
what is final exam time? can we take final exam in early time? like 13:00.

**Comment by jeehoonkang** [comment]
@amityaffliction Sorry for not replying for a long time. I think I am not in a position to answer your question; would you please ask @gilhur at a class?

Jeehoon
