### ISSUE TITLE
Make sure  make  works without errors.

### ISSUE THREAD

**Issue by justlaugh05** [snu-sf/pl2015#49]
My assignment in the coqIDE can navigate until the end with Ctrl+alt+->
And the compile buffer works.
But when I try to 'make' in coqIDE, the program freezes.
Also when I try make or makefile in bash, it does not work as well.
![default](https://cloud.githubusercontent.com/assets/9108550/6936746/52fc2370-d890-11e4-80f2-c62482f571e4.JPG)
I have submitted already, but I am not sure what is wrong.
Would I have to fix something and submit again?
or if the navigation works and the 'compile buffer' works would I be fine?

**Comment by jeehoonkang** [comment]
Would you please run `make` instead of `./Makefile`? `make` is the right way to run Makefile.

Jeehoon

**Comment by jeehoonkang** [comment]
Also, please paste code in text (not in image). Read GitHub-flavored Markdown manual.

**Comment by justlaugh05** [comment]
At the very top of the image I ran 'make' and it did not work.. 
Sorry I will paste the code in text next time!

**Comment by jeehoonkang** [comment]
I believe you don't have `make`, as said: "make: command not found."

You have to install `make` first.
