### ISSUE TITLE
Issue about importing blt_nat from Basics.v

### ISSUE THREAD

**Issue by jaewooklee93** [snu-sf/pl2015#54]
Problem 4 of Assignment 4 is to define the following filter.

``` Coq
(* Assignment04.v *)
Definition filter_even_gt7 (l : list nat) : list nat :=
  (* FILL IN HERE *) admit.
```

Naturally, I want to use function `blt_nat` from `Basics.v`, however, in `Basics.v`, `blt_nat` is not defined by default and left as an exercise.

``` Coq
(* Basics.v *)
Definition blt_nat (n m : nat) : bool :=
  (* FILL IN HERE *) admit.
```

That is different to cases of functions `evenb`, `beq_nat` or `ble_nat`, which are already defined by default.

``` Coq
(* Basics.v *)
Fixpoint ble_nat (n m : nat) : bool :=
  match n with
  | O => true
  | S n' =>
      match m with
      | O => false
      | S m' => ble_nat n' m'
      end
  end.
```

Then my question is whether we are able to use the undefined function in the exercise of `Basics.v` such as `blt_nat`, or we can use only functions previously defined by author, such as `ble_nat`. Without providing the definition of `blt_nat` in `Basics.v`, the code below doesn't work if we use `blt_nat`.

``` Coq
Example test_filter_even_gt7_1 :
  filter_even_gt7 [1;2;6;9;10;3;12;8] = [10;12;8].
Proof. reflexivity. Qed.
```

Of course, I will try to use only previously given function for safety. But I think there may be other students who involuntarilty use `blt_nat` as well and encounter incomprehensible error message, so I want to post this issue to make it clear.

**Comment by jaewooklee93** [comment]
Plus, I encountered the problem which directly uses `rev_involutive`, 

``` Coq
(* Lists.v *)
Theorem rev_involutive : forall l : natlist,
  rev (rev l) = l.
Proof.
  (* FILL IN HERE *) Admitted.
```

However, here we can use this theorem without any obstacle even without proving it, because we `Admitted` it. How about this case? Can we use this theorem?

**Comment by jeehoonkang** [comment]
@jaewooklee93
- Thank you for your considerate opinion. As Jaewook said, students should avoid using `blt_nat` since its definition is admitted and we cannot prove properties on it.
- You cannot use theorems in `Lists.v`, as said `(\* DO NOT Require Import other files. *)'.

Jeehoon

**Comment by jaewooklee93** [comment]
Thank you for your reply.

However, our file `Assignment04.v` already has a line of  `Require Import Poly.` in itself, and `Poly.v` has `Require Import Lists.`.  So I can call the theorem `rev_involutive` without directly adding any importing directive.

**Comment by jeehoonkang** [comment]
@jaewooklee93 Sorry for my misunderstanding. I will reply soon.

**Comment by jeehoonkang** [comment]
You can use lemmas admitted in the `Require Import`ed files.

**Comment by jaewooklee93** [comment]
Thank you very much.

Jaewook Lee

**Comment by rhs0266** [comment]
rev_involutive 처럼 Admitted 되어 있는 것은 과제 코드 내부에 정의하여 써도 되는 뜻인가요?

과제 중반에
`(** Hint: you can use [apply] with previously defined lemmas, not
    just hypotheses in the context.  Remember that [SearchAbout] is
    your friend. *)`
와 같은 문구가 의미하는 것은 rev_involutive를 증명하고 사용해도 된다는 뜻으로 보이는데,
`rewrite -> rev_involutive in H'`
와 같은 문구를 증명 과정에 사용 가능한가요?

**Comment by jeehoonkang** [comment]
@rhs0266
- Yes you can use, for example, `rev_involutive` in Assignment 04.
- Please ask in English so that non-Korean speakers could understand :-)
- Please make your repository private.

Jeehoon
