### ISSUE TITLE
Can I add additional things(lemmas, functions...) to solve given problems?

### ISSUE THREAD

**Issue by 201313381lmk** [snu-sf/pl2015#55]
I added new functions and lemmas in Assignment04.v and they work without trouble in CoqIde. As far as I know, most TAs use automatic compiling&grading programs to check students' homeworks. So I wonder: is it okay to add new functions and lemmas? Or does it cause problems in the grading program?

**Comment by jeehoonkang** [comment]
I will do my best to recognise the lemmas and functions you added.....................

Best,
Jeehoon
