### ISSUE TITLE
Can I use 'auto' tactic for HW(assignment) and exams?

### ISSUE THREAD

**Issue by ik1ne** [snu-sf/pl2015#57]
Can I use 'auto' and 'tauto' tactics?

**Comment by jeehoonkang** [comment]
Yes.

**Comment by ik1ne** [comment]
@jeehoonkang Thank you! One more thing to ask, should I close this issue since it is resolved?

**Comment by jeehoonkang** [comment]
Don't worry; I will close the issue!

**Comment by jaewooklee93** [comment]
It is quite surprising that we can use `tauto`. Since the power of `tauto` is too strong, the most of exercises in `Logic.v` can be solved even in simple one line `unfold iff; unfold not; tauto.`...

**Comment by gilhur** [comment]
You are not allowed to use 'tauto' yet.
More specifically, you are not allowed to use the following tactics.

[tauto], [intuition], [firstorder], [omega]

At some point later, I will allow to use them, but NOT YET!
