### ISSUE TITLE
Indentation problem in emacs with ProofGeneral

### ISSUE THREAD

**Issue by minitu** [snu-sf/pl2015#59]
I'm having a problem with indentation in emacs with ProofGeneral.
It's supposed to insert 2 spaces or indent the same way as the above line when I press TAB but it often inserts a lot more spaces than that.
I've searched for the solution online, and found that if I insert `(require 'coq)` in .emacs the indentation works properly but ProofGeneral does not execute.
I wonder if anyone is experiencing the same problem and has found a solution to it.

**Comment by jeehoonkang** [comment]
It is a well-known problem that ProofGeneral sometimes cannot guess the precise size of spaces. I am not sure it is the case for you. To further investigate your case, I would like you to come to my office (mail pl2015@sf.snu.ac.kr for making appointment!).

Jeehoon
