### ISSUE TITLE
questions about installing coq

### ISSUE THREAD

**Issue by amityaffliction** [snu-sf/pl2015#6]
1. There was dependency problem when i tried to install coqide in Ubuntu and I don't know how to solve it(using ocaml 4.02.0). I guess coqide in linux is available only using coq8.4pl3.
   will there be any problem using just coqc and vi instead of using coqide?
2. is it okay to use coq8.4pl3 which is currently installed in school martini server?
   i wonder if there will be any version problems doing further homework

thank you for reading

**Comment by jeehoonkang** [comment]
- I am currently talking with Bacchus members to get Coq 8.4pl5 installed in martini. It will be installed no later than the first homework's due date.
- You can install Coq 8.4pl5 by:
  - Download tarball file.
  - `./configure -coqide opt`
  - `make`
  - `make install`
  - Make sure that before installing, you have lablgtk2 installed already. In Ubuntu, install via [https://launchpad.net/ubuntu/+source/lablgtk2](https://launchpad.net/ubuntu/+source/lablgtk2). In CentOS/Fedora, install via [http://pkgs.org/download/ocaml-lablgtk-devel](http://pkgs.org/download/ocaml-lablgtk-devel).

I will update README.

**Comment by amityaffliction** [comment]
thank you

**Comment by jeehoonkang** [comment]
8e18e3d573eb0b8fb5b83eb648e5f1664ca002b8
