### ISSUE TITLE
About dividing assignment files

### ISSUE THREAD

**Issue by fortunist** [snu-sf/pl2015#62]
I think it is too uncomfortable for students.
There is a possible situation like this : I defined a lemma for some theorems to prove, and it works well when I compile. However, it makes problem in new grading method because the lemma is not in the skeleton files. To avoid this situation, I have to define the lemma in all files which have a theorem using the lemma. I think it is too uncomfortable.
Furthermore, I think it is okay using one theorem to prove in other files' theorems because of <code>admit.</code>(if not, it makes further uncomfortability) but to find the theorem, I have to open and open and open other files again or use <code>SearchAbout</code> whenever using the theorem. I just scrolled a file in previous assignments. I think it is too uncomfortable.

**Comment by jeehoonkang** [comment]
- I understand it is a bit inconvenient to duplicate lemmas. I truly am sorry for this.
- On the other hand, I think `SearchAbout` is the right way to find lemmas related to a certain definition. it can be a little bit more inconvenient than just scrolling up. But `SearchAbout` scales up to (almost) arbitrary number of Coq files, while scrolling up does scale up to only one short file. I would like students to use `SearchAbout` more and more!

Jeehoon

**Comment by alkaza** [comment]
why was it decided to separate problems?

**Comment by jeehoonkang** [comment]
@alkaza Mostly for the ease of grading..

**Comment by justlaugh05** [comment]
I do feel that the TA's grading should be simplified. I mean, it is a lot of people!
But is there really no other way for you to grade easily? 
There are two main problems in my case..
1. The sf folder is getting incredibly crowded. If it is 39 problems, then it becomes 39*3. nearly 120 files after make. just for assignment 5! I've noticed that the number of questions are growing in an almost exponential rate... If it is 120 files for one assignment, after the semester it would be something to the thousands?? It is quite a nuisance.
2. I wanted to recall how I used a certain tactic. For example, I know I did something with 'destruct' before to solve a similar issue, but I don't remember exactly what I did. So I want to look back on my previous solutions, but I have no idea which problem I used that tactic for! There are like 30 different choices, and after opening and opening and opening... it tends to get quite frustrating. If it was all in one file, I could just search for 'destruct' and it would show me quickly. 

But again, if there really is no other way, I guess we would have to get used to doing this. But can you at least solve problem for my first problem? That doesn't seem like too much work.. or is it?

**Comment by jeehoonkang** [comment]
@justlaugh05 Thank you for your kind opinion. Gil and I will try best for students' convenience.

Jeehoon

**Comment by jeehoonkang** [comment]
@justlaugh05 I considered grouping files into a folder `Assignment06`, it alters the behavior of `make`. So I put all the files in the `sf` directory. Sorry for inconvenience.
