### ISSUE TITLE
Is it okay to define another Lemma in HW files?

### ISSUE THREAD

**Issue by ik1ne** [snu-sf/pl2015#64]
For example, in the assignment no.32, I did it like this:
Lemma A: .....Qed.
Lemma B: .....Qed.
Theorem Sn_le_Sm__n_le_m : ......(used A and B) Qed.

Is it okay? Or should I move A&B inside Theorem Sn_le_Sm__n_le_m?

**Comment by jeehoonkang** [comment]
Yes you can.
