### ISSUE TITLE
Sudden screen scrolling, CoqIde windows

### ISSUE THREAD

**Issue by AdamBJ** [snu-sf/pl2015#65]
I've been experiencing some issues while using CoqIde in Windows where when I click on a line on code to edit it or select it, the screen jumps randomly to another part of the file. Has anyone else experienced this problem? If so, has anyone else figured out a fix for it?

Thanks

**Comment by alkaza** [comment]
It jumps back to where u were, before u started scrolling, The only way is
to 'click' on a place where you want to start selecting from and then after
it jumps, u push space or ctrl+shift+->, doesn't matter, and it will go to
the place you were looking at. Hope this helps.

**Comment by AdamBJ** [comment]
I'll give it a try, thanks!

**Comment by jeehoonkang** [comment]
Any progress on this issue?

**Comment by AdamBJ** [comment]
@alkaza 's suggestion worked for me.
