### ISSUE TITLE
Separate assignment late submission.

### ISSUE THREAD

**Issue by alkaza** [snu-sf/pl2015#67]
Since you separated all the problems, is it possible for us to submit the ones we solved on time and then submit the rest later? 
For example, I haven't solved assignment 26 and 27, but solved the rest. 
If I update them after the deadline and you will be be collecting late submissions, will my whole homework be penalized for the lateness or only these two problems?

**Comment by jeehoonkang** [comment]
Yes you can. Your score for an exercise is the maximum of the first submission and the delay submission (30% discounted).

Jeehoon
