### ISSUE TITLE
make command using Windows

### ISSUE THREAD

**Issue by AdamBJ** [snu-sf/pl2015#68]
I've been using CoqIde to do the compilation of my.v files manually, and am finally sick of all the conflicts I 'm running into and want to automate the process with Make (I'm on Windows 7 by the way).To that end, I've installed Make for Windows - GnuWin32, and have made sure that my system path variable is set correctly (i.e. it includes both the GnuWin32 bin and the MinGW bin). However, when I open up cmd and run make clean in the sf directory, I get an error saying
 make (e=2): The system cannot find the file specified.
 make: **\* [clean] Error 2

I did some research, and it seems like the problem might be the line 
includecmdwithout@ = $(eval $(subst @,$(donewline),$(shell { $(1) | tr -d '\r' | tr '\n' '@'; })))
in the makefile we're given. It seems like it won't work from the Windows command prompt as it uses sh/bash and not cmd/batch. Does any one know a way around this problem?

**Comment by jaewooklee93** [comment]
I guess that we don't need to install `make` manually on Windows because CoqIDE already contains that feature.

How about trying this? **Compile > Make**

![default](https://cloud.githubusercontent.com/assets/11328376/7195499/9a87f54e-e4fb-11e4-82d7-04e5e04bac54.png)

If you don't have `makefile` in your directory, do **Compile > Make makefile** first, that automatically creates `makefile` for all source files in the directory. however, TA always provide a proper `makefile`, so you can simply use it.

**Comment by fortunist** [comment]
How about running make clean on git bash?

**Comment by AdamBJ** [comment]
@jaewooklee93 So if I do that it'll create a .vo file for each .v file in the directory?

**Comment by AdamBJ** [comment]
@fortunist No luck using git bash. Thanks for the suggestions though.

**Comment by fortunist** [comment]
Hmm... Are the error messages same on both cmd and git bash? If the message of git bash is like "C:\program: interrupt/exception caught...", I have a solution.

**Comment by ik1ne** [comment]
In my case, coqide's make(F6) did nothing until I added Program Files\coqide-?.?.?\bin for cmd path.

**Comment by AdamBJ** [comment]
@fortunist when I use git bash it says "Interrupt/Exception caught..." followed by some error code written in hexidecimal.

**Comment by AdamBJ** [comment]
When I use Make in CoqIde the program just freezes!

**Comment by fortunist** [comment]
Well, I think it can be solved by re-installing git for windows with new installation path which does not have parenthesises. (e.g. C:\Program Files (x86)\git -> C:\git)
Then, you can use make command on git bash, and <code>make clean</code> work properly unlike cmd.

I had experienced that error too, and I found there is such a bug in GNUWin32.

I sincerely hope this can solve your problem.

**Comment by alkaza** [comment]
I had the same problem, because Make was not installed, it wouldn't work in
cmd, etc.
After I installed Make, everything started to work.

**Comment by AdamBJ** [comment]
@fortunist That did it! I can run make commands using the git bash. Thanks!
