### ISSUE TITLE
Make your repository private

### ISSUE THREAD

**Issue by jeehoonkang** [snu-sf/pl2015#7]
Hi all,

As described [here](https://github.com/snu-sf/pl2015/blob/master/Homework.md#how-to-begin), please make your repository private. The contents of the links basically ask you to:
- "Request a discount" from https://education.github.com
- Wait for (at most) a day for the discount to be granted.
- Change your repository to private one in the repositories' `Settings` > `Danger Zone`.

Jeehoon

**Comment by jaewooklee93** [comment]
I "requested a discount" last Thursday at the lab session, but it is still pending...

**Comment by jeehoonkang** [comment]
@jaewooklee93 

I think that's probably because it is a weekend..
Then let's wait another day or two.

Jeehoon

**Comment by yookoon** [comment]
I still cannot get the request approved. It's still 'pending'

**Comment by jeehoonkang** [comment]
Would anybody please let me know how you applied your private repositories? Pending so far seems strange for me, and I would like to know what is the problem.

**Comment by ntopia** [comment]
Hi.
Follow this link. https://education.github.com/contact
In FAQ section > "How long will it take to process my discount request?",
they said that the wait time could be a few weeks.

By my friend who applied 'Github education program', he waited a month in pending.

**Comment by jeehoonkang** [comment]
@ntopia Thank you for letting me know. I mailed to the GitHub Education team and requested a fast transaction for your applications. If they don't give you discounts at a due time, I will make an alternative measure ASAP.

Once more, thank you. Jeehoon

**Comment by jeehoonkang** [comment]
Hi all, I contacted GitHub Education team, and they said it will be helpful to contact via: https://education.github.com/contact If you think it takes too much time to get granted, do:
- contact https://education.github.com/contact and
- say something like:

```
Hi GitHub Education Team,
I am YOURNAME, a student from Seoul National University.

This semester I take Programming Languages course, 
and to attend the the course, I have to prepare for a private repository.

So I applied a discount from education.github.com, but I could not get an approval.
As the first assignment will be issued next week, I will need a free repository soon.

So may I ask if you could approve my application sooner than usual?
My TA (@jeehoonkang) said he asked Mr. Sanicki (@sanicki) to help me, so I contacted via this channel.

Thanks,
YOURNAME
```

Obviously, you may have to replace `YOURNAME` with your name.

Jeehoon

**Comment by liveseongho** [comment]
I requested my personal e-mail(naver.com). maybe that's why my request is still pending.. How can I cancel my request?

**Comment by jeehoonkang** [comment]
@ch7457 Just apply one more time.

Jeehoon

**Comment by liveseongho** [comment]
we cannot apply one more time while we're pending

**Comment by jeehoonkang** [comment]
@ch7457 Ah..
in that case, 
- confirm your SNU email in GitHub https://help.github.com/articles/verifying-your-email-address/
- contact via https://education.github.com/contact and tell them you have SNU email but applied for education program with commercial email address,
- in addition to the template I gave (begging with `Hi GitHub Education Team,` above).

Jeehoon

**Comment by r4ddek** [comment]
I am still waiting for an answer. I have sent the suggested email already, but no answer until now.
As soon as I get my request accepted I will comment here.
Thank you.
