### ISSUE TITLE
Attendance

### ISSUE THREAD

**Issue by jeehoonkang** [snu-sf/pl2015#70]
Here is attendance:

https://docs.google.com/a/sf.snu.ac.kr/spreadsheets/d/1LzOLx22lF3N31D9RDS20Ec8ub_Rq6IA3utD8CNMk9CQ/edit#gid=613705988
- If you had an official leave, please let me know.
- This is tentative: I will check the photos.

Jeehoon

**Comment by jaewooklee93** [comment]
I've been in the class on 4/16 and I'm sure that I'm in the photo, but I didn't write my number in the paper. I think that paper didn't come to my place. Is it okay?

**Comment by jeehoonkang** [comment]
@jaewooklee93 Currently I haven't received the photos. I believe there are more students who couldn't write their student IDs. I will take care of this problem.

Jeehoon

**Comment by sangholee12** [comment]
As I said via e-mail, I left the class in the middle on April 9th with the permission of Professor Hur because of exam, but I had forgotten to tell you and other assistants.

**Comment by yookoon** [comment]
I left the class in the middle on April 9th with the permission of Professor Hur because of Statistics exam
 together with sangholee12. Please account me too.

**Comment by jeehoonkang** [comment]
- Attendance status is updated until 5/19: https://docs.google.com/spreadsheets/d/1LzOLx22lF3N31D9RDS20Ec8ub_Rq6IA3utD8CNMk9CQ/edit#gid=613705988
- We will check the photo, too.
- I believe I processed every request for official leaves; it not, please let me know.

Jeehoon
