### ISSUE TITLE
Do we have to use OCaml version 4.01.0?

### ISSUE THREAD

**Issue by jaewooklee93** [snu-sf/pl2015#8]
In the instruction given in the file Coq.md, it seems to be necessary to use OCaml version 4.01.0.
But the command "apt-get install" in Ubuntu installs the version 4.02.1, not 4.01.0.
With 4.02.1, it works, but I see many warning messages of deprecation during the installation of Coq.
Since I'm not familiar with Linux, I have no idea with how to install the older version of OCaml.
How can I solve it?

**Comment by jaewooklee93** [comment]
I also failed to install coqide in my computer...
How can I use this link?
https://launchpad.net/ubuntu/+source/lablgtk2

**Comment by jeehoonkang** [comment]
- 4.02.1 works fine.
- First, install libgtk2: `sudo apt-get install libgtk2.0-dev` or `yum install gtk2-devel`
- `opam install lablgtk`
- `./configure -coqide opt` Then it should say `LabelGtk2 found by ocamlfind, native threads: native CoqIde will be available.`

**Comment by jeehoonkang** [comment]
8e18e3d573eb0b8fb5b83eb648e5f1664ca002b8

**Comment by jaewooklee93** [comment]
Thank you very much. It works pretty well with revised instructions.
