### ISSUE TITLE
Midterm exam location today

### ISSUE THREAD

**Issue by wonook** [snu-sf/pl2015#81]
Hi,
I have a question regarding the midterm exam today. Since we have quite a number of students, I have a feeling that not all of us will fit in the 311-1 소프트웨어실습실. Will there be a solution regarding this issue?

**Comment by jeehoonkang** [comment]
There are 62 students and 60 computers. I told 5 students to bring their own notebooks.

Jeehoon

**Comment by wonook** [comment]
I think there are some computers that aren't working properly though. Have the computers been checked? Just to be sure!

**Comment by jeehoonkang** [comment]
@wonook I appears that there were enough seats :-) thank you for your concerns.
