### ISSUE TITLE
Is long compile time ok?

### ISSUE THREAD

**Issue by jaewooklee93** [snu-sf/pl2015#83]
When I solved `Assignment07_02.v`, I used several number of `try omega`, but it seems that `omega` takes relatively longer time than others tactics. So now compilation takes almost 10 seconds at my machine. I guess that this phenomenon will continue to appear as the complexity of proof increases. Thus, I want to clarify whether such long compile time is available or not, at this point.

**Comment by jeehoonkang** [comment]
10 seconds would be fine.
10 minutes will be a problem.

Jeehoon

**Comment by jaewooklee93** [comment]
Thank you. It's quite weird that even `Qed` took several seconds.

**Comment by jeehoonkang** [comment]
@jaewooklee93 That's because `Qed` re-checks the proof term. For some times, `Qed` alone takes more time than the proof between `Proof` and `Qed`.

Jeehoon
