### ISSUE TITLE
destructing sumbools

### ISSUE THREAD

**Issue by AdamBJ** [snu-sf/pl2015#85]
Say I want to prove something like : `(if eq_id_dec x x then n else st x) = n`. What I'd like to do is prove some lemma like `eq_id_dec = true`. How can we do this with sumbools though? I know an alternative is to do destruct (eq_id_dec x x, but  I get stuck on the case where x!=x so I'd like to avoid using destruct.

**Comment by jeehoonkang** [comment]
If you have `H: x <> x`, then `exfalso; apply H; auto` will solve the goal.

Jeehoon

**Comment by jaewooklee93** [comment]
Thank you. I always used `assert (x=x)` and then drew contradiction. Your method is much simpler.

**Comment by jeehoonkang** [comment]
It would be also nice to state something like:
`Lemma eq_id_dec_true {A} x (a1 a2:A): (if eq_id_dec x x then a1 else a2) = a1.`

**Comment by AdamBJ** [comment]
The first way worked for me, thanks Jeehoon.
