### ISSUE TITLE
How can I unfold some portion of my goal?

### ISSUE THREAD

**Issue by ik1ne** [snu-sf/pl2015#88]
While solving 7_2, I managed to simplify my goal into this:
`AMult (optimize_1mult a1) (optimize_1mult a2) = optimize_1mult (AMult a1 a2)`
And this must be very simple to proof, since `Fixpoint optimize_1mult` has `match a with | AMult e1 e2 ...` so I can `simpl`(or `unfold optimize_1mult`) right hand side only and then use `reflexivity`.
But, when I try `simpl` tactics, it also unfolds `optimize_1mult` in the left side, making the goal nearly impossible to proof without induction/destruct.
Do I have to use induction for this goal?

**Comment by jeehoonkang** [comment]
Try `unfold optimize_1mult at 1`, `unfold optimize_1mult at 2`, etc.

**Comment by jaewooklee93** [comment]
`(optimize_1mult (AMult a1 a2)))` is not the same as `(AMult (optimize_1mult a1) (optimize_1mult a2))` The counterexample is the case of `a1=ANum 1` and `a2=ANum 2`.

_(optimize 1)×(optimize 2)_=**1×2** doesn't give you the same formula as _optimize (1×2)_=**2**.

**Comment by jeehoonkang** [comment]
May I ask if there is any progress on this issue?

**Comment by jaewooklee93** [comment]
I think it is already ended, since it dealt with the last assignment.

**Comment by ik1ne** [comment]
Oh, yes, I found that I was proving wrong way, so I haven't used unfolding some portion in assignment 7.
However, I used it in assignment 08. Thank you!
