### ISSUE TITLE
Using the automatic grader

### ISSUE THREAD

**Issue by AdamBJ** [snu-sf/pl2015#90]
When I try ./grader.sh in git bash I get the error "./grader.sh: line 34: seq : command not found"

I'm running windows and installed sed for windows from this source: http://gnuwin32.sourceforge.net/packages/sed.htm. Does anyone have a suggestion about how this might be resolved? Thanks.

**Comment by alkaza** [comment]
For me, "seq.exe has stopped working" happens

**Comment by jeehoonkang** [comment]
I recommend you to test in `martini.bacchus.org`, a Linux machine with Coq installed.

Jeehoon

**Comment by alkaza** [comment]
Could you explain how to do that?

**Comment by jeehoonkang** [comment]
I will recommend you another way. Replace:

```
for i in $(seq -f "%02g" 1 ${NPROBS}); do
```

with:

```
for i in "01 02 03 04 05 06 07 08 09 10"; do
```

Jeehoon

**Comment by fortunist** [comment]
You can use CoreUtils for Windows. It contains seq for windows which works well.
http://gnuwin32.sourceforge.net/packages/coreutils.htm

**Comment by AdamBJ** [comment]
@fortunist your suggestion seemed to work! But I'm not sure how to interpret the results. Here is what I'm getting:

![image](https://cloud.githubusercontent.com/assets/8980400/7603494/40d76d26-f96f-11e4-8ab5-366bf8426b72.png)

@jeehoonkang How do we know if a question is correct or not?

**Comment by fortunist** [comment]
No error means the problem files are compiled well. If you correctly overwrote your assignments to submission directory, those are correct.

> jeehoonkang commented 24 days ago
> 
> I made an automatic grader: http://sf.snu.ac.kr/jeehoon.kang/pl2015/Assignment05_grader.tar.gz
> - You have to use it with bash, and sed should be installed in your machine. You can use these programs in the martini.snucse.org and midori.snucse.org servers.
> - Place your Assignment05_??.v files in submission folder. NOTE: original folder should be intact.
> - Run by ./grader.sh.
> - If your submission has a compilation error, then an error message will be present.
> 
> Hope this grader will help you prepare a good submission.
> Jeehoon

**Comment by AdamBJ** [comment]
Ok, thanks for the info guys!
