### ISSUE TITLE
Would you check my attendance status?

### ISSUE THREAD

**Issue by LeeGyeongGeon** [snu-sf/pl2015#94]
Hello.

I noticed that my attendance status is 'x' on 2015. 4 .16 class.

Actually, I attended that class, but I didn't signed on the paper.
If you check the photos, I'm sure you can find me.
Would you check those and revise attendance status for me?
(My student ID is 2011-12823).

Thank you.

**Comment by jaewooklee93** [comment]
Me, too. :)

For the same date 2015/4/16 and my ID is 2011-11772.

**Comment by jeehoonkang** [comment]
Thank you for your feedback; I applied.
